language: php

php:
        - 5.4
        - 5.5
        - 5.6
        - hhvm

cript:
        - travis_retry composer install --prefer-source --no-interaction --dev

script:
        - vendor/bin/phpspec run --config=phpspec.yml --no-interaction
